valor = input('Digite algo: ')
print('O tipo primitivo deste valor é ', type(valor))
print('O valor digitado é um número? ',valor.isnumeric())
print('O valor digitado é alfanumérico? ', valor.isalnum())
print('O valor digitado é alfabético? ', valor.isalpha())
print('O valor digitado só tem espaço? ', valor.isspace())
print('O valor digitado está em maiusculas? ', valor.isupper())
print('O valor digitado está em minúsculas? ', valor.islower())
print('O valor digitado está capitalizado? ', valor.istitle())
